### ISSUE TITLE
admin/login  Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by roboto-cloud** [cezerin/cezerin#352]
Hi, someone know how make it work?

I use: using [JWT.IO](https://jwt.io/) for **jwtSecretKey** with this data:

```
db.tokens.insert({
  is_revoked: false,
  date_created: new Date(),
  expiration: 72,
  name: 'Owner',
  email: 'demo@domain.test',
  scopes: ['admin']  
});
```

And server.js with this data:

```
// config used by server side only
module.exports = {
  // used by Store (server side)
  apiBaseUrl: `http://localhost:3001/api/v1`,

  // used by Store (server and client side)
  ajaxBaseUrl: `http://localhost:3001/ajax`,

  // Access-Control-Allow-Origin
  storeBaseUrl: `http://localhost:3000`,

  // used by API
  adminLoginUrl: '/admin/login',

  apiListenPort: 3001,
  storeListenPort: 3000,

  // used by API
  mongodbServerUrl: 'mongodb://127.0.0.1:27017/shop',

  smtpServer: {
    host: 'smtp.domain.test',
    port: 587,
    secure: false,
    user: 'hello@domain.test',
    pass: 'domain.test.psw',
    fromName: 'domain.test.name',
    fromAddress: 'domain.test'
  },

  // key to sign tokens
  jwtSecretKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiT3duZXIiLCJlbWFpbCI6ImRlbW9AZG9tYWluLnRlc3QiLCJhZG1pbiI6dHJ1ZX0.8ivuNfbUB2R9q2YyWCi7lwL73Xks0o8IVvcja78t8So',

  // key to sign store cookies
  cookieSecretKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',

  // path to uploads
  categoriesUploadPath: 'public/content/images/categories',
  productsUploadPath: 'public/content/images/products',
  filesUploadPath: 'public/content',
  themeAssetsUploadPath: 'theme/assets/images',

  // url to uploads
  categoriesUploadUrl: '/images/categories',
  productsUploadUrl: '/images/products',
  filesUploadUrl: '',
  themeAssetsUploadUrl: '/assets/images',

  // store UI language
  language: 'en',

  // used by API
  orderStartNumber: 1000,

  developerMode: false
}

```

**Comment by restmount** [comment]
Hi @roboto-cloud 
To receive sign in email, you need:
1. set ```smtpServer```
2. set jwtSecretKey for example 
``` jwtSecretKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9'```
this is secret key, not jwt itself
3. developerMode: false
4. have token data in MongoDB
```
db.tokens.insert({
  is_revoked: false,
  date_created: new Date(),
  expiration: 72,
  name: 'Owner',
  email: 'demo@domain.test',
  scopes: ['admin'] 
});
```

**Comment by restmount** [comment]
Set correct jwtSecretKey.
If this not help, check SMTP.

**Comment by roboto-cloud** [comment]
Hi @restmount, the SMTP service are working on the external service, how get trace or log of the mail into cezerin container? here an capture of the up and running mail service on the port 587 with STARTTLS

this is my **step by step** jwtSecretKey, jwtSecretKey and developerMode are in server.js what is listed on docker volume. I load the token using mongo shell

**1** compose up cezerin docker

```
version: '3.5'

networks:
  traefik-00:
    name: traefik-00
    external: true

services:
  domain.test:
    restart: always
    container_name: domain.test
    image: cezerin/docker-cezerin:0.31.1
    expose:
      - '80'
    labels:
      - 'traefik.backend=domain.test'
      - 'traefik.frontend.rule=Host:domain.test'
      - 'traefik.docker.network=traefik-00'
      - 'traefik.port=80'
    volumes:
      - ../live/config/server.js:/var/www/cezerin/config/server.js
    networks:
      - traefik-00
```

**2** go inside
`docker exec -it demo.tt bash`

**3** load the token into mongo
mongo shop
```
db.tokens.insert({
  is_revoked: false,
  date_created: new Date(),
  expiration: 72,
  name: 'Owner',
  email: 'demo@domain.test',
  scopes: ['admin'] 
});
```

**don't get the mail**

the server.js mounted have this data:
```
// config used by server side only
module.exports = {
  // used by Store (server side)
  apiBaseUrl: `http://localhost:3001/api/v1`,

  // used by Store (server and client side)
  ajaxBaseUrl: `http://localhost:3001/ajax`,

  // Access-Control-Allow-Origin
  storeBaseUrl: `http://localhost:3000`,

  // used by API
  adminLoginUrl: '/admin/login',

  apiListenPort: 3001,
  storeListenPort: 3000,

  // used by API
  mongodbServerUrl: 'mongodb://127.0.0.1:27017/shop',

  smtpServer: {
    host: 'mail.domain.test',
    port: 587,
    secure: true,
    user: 'hello@domain.test',
    pass: 'demo.pass',
    fromName: 'domain.test',
    fromAddress: 'hello@domain.test'
  },

  // key to sign tokens
  jwtSecretKey: 'eyJhbGciOiJIUzI1',

  // key to sign store cookies
  cookieSecretKey: 'eyJhbGciOiJIUzI1',

  // path to uploads
  categoriesUploadPath: 'public/content/images/categories',
  productsUploadPath: 'public/content/images/products',
  filesUploadPath: 'public/content',
  themeAssetsUploadPath: 'theme/assets/images',

  // url to uploads
  categoriesUploadUrl: '/images/categories',
  productsUploadUrl: '/images/products',
  filesUploadUrl: '',
  themeAssetsUploadUrl: '/assets/images',

  // store UI language
  language: 'en',

  // used by API
  orderStartNumber: 1000,

  developerMode: false
}
```
thanks in advance,
